name: CI

on:
  pull_request:
jobs:
  main:
    name: Typecheck and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Type Check Code Base
        run: npm run tsc

      - name: Lint Code Base
        run: npm run lint
