name: Testing

on:
  pull_request:
    paths:
      - "__test__/**"
      - "src/pages/api/v1/**"
      - "src/lib/middleware.ts"
jobs:
  main:
    name: Test with Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run jest tests
        run: npx jest ----passWithNoTests
