name: CI

on:
  pull_request:
    paths:
      - ".github/**"
      - "__test__/**"
      - "pages/api/v1/**"
      - "lib/middleware/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Test api
        run: npx jest
